pkg/event_handler/cd_handler.go, pkg/lib/dynatrace.go, pkg/lib/dynatrace_events.go
This PR fixes issue #107.
In addition, I've refactored the `cd_handler.go` such that it also uses `dtHelper` to send api calls to Dynatrace.
=> #107 Refactor sendEvent method for Dynatrace

pkg/event_handler/problem_handler.go, pkg/lib/dynatrace.go, pkg/lib/dynatrace_api_models.go, pkg/lib/one_agent.go
This avoids handling events that were sent out by the dynatrace-service itself (i.e. infinite loops)
Additional fixes:
- Remove event type filter from alerting profile
- Fixed DT operator version to 0.6.0
=> #127 only handle events that come from the Dynatrace tenant

pkg/lib/one_agent.go
due to the changes made in PR https://github.com/keptn-contrib/dynatrace-service/pull/138 the availability of the PaaS token has been added to the segment where Dynatrace is being deployed in the cluster.
=> #137 check availability of credentials during DT setup

go.mod, go.sum, pkg/event_handler/action.go, pkg/event_handler/action_triggered.go, pkg/event_handler/handler.go, pkg/lib/problem_comment.go, test-events/action-finished.http, test-events/action-triggered.http
This PR closes [#1818](https://github.com/keptn/issues/1818)
The dynatrace-service now reacts to `action.triggered` and `action.finished` events, and - if those events contain a Dynatrace Problem ID - sends a comment to the referenced problem.
=> #1818 send problem comments when actions are triggered/finished

pkg/lib/dynatrace.go
Closes #150 
In this PR, the dynatrace-service will deploy the version 0.8.0 of the dynatrace oneagent operator
=> #150 updated DT operator version

deploy/manifests/dynatrace-service/dynatrace-service.yaml, pkg/event_handler/configure_monitoring.go
This PR 
- corrects the WebSocket URL to /websocket
- refactors the WebSocket URL into an env-variable
=> Correct WebSocket URL to /websocket

deploy/service.yaml, pkg/event_handler/configure_monitoring.go, pkg/lib/one_agent.go, releasenotes/releasenotes_develop.md
Help the user, when DT OneAgent is not installed: 
```
Dynatrace OneAgent Operator is not installed on cluster
The behavior has changed and Dynatrace OneAgent Operator will NOT be installed automatically.
If you want to roll-out the OneAgent, please follow the instructions as provided here:
1.) Please follow the instructions as provided here:
https://www.dynatrace.com/support/help/technology-support/cloud-platforms/kubernetes/deploy-oneagent-k8/
2.) Then, re-deploy the dynatrace-service:
kubectl apply -f https://raw.githubusercontent.com/keptn-contrib/dynatrace-service/<VERSION>/deploy/service.yaml  
--------------------------------------------------------------------------------------------------
```
=> Improved info message and update of release notes

pkg/common/common.go
when validating the Keptn API Connection we also allow insecure certificates
=> Validating the Keptn API Connection - master

cmd/main.go
Closes #171 
To avoid crashes as a consequence of a failed Keptn API connectivity check (which is bound to happen if the LoadBalancer used to expose the Keptn API), a warning message is printed in the logs instead of exiting.
=> #171 don't exit if API connection check goes wrong

.github/workflows/CI.yml
Signed-off-by: Christian Kreuzberger <christian.kreuzberger@dynatrace.com>
Based on https://github.com/keptn/keptn/issues/2824 this PR introduces a new GH action for extracting the branch name, therefore reducing the CI workflows complexity within this repository.
=> Use keptn/gh-action-extract-branch-name

pkg/event_handler/problem_handler.go
Ad #287: 
remediation.triggered needs to be sent for a stage, triggering the sequence for this stage.
Thanks @bacherfl for the feedback!
=> #287 Send out remediation.triggered for a stage

cmd/main.go, go.mod, go.sum, pkg/adapter/dynatrace_config_getter.go, pkg/adapter/mock/dynatrace_config_mock.go, pkg/event_handler/action.go, pkg/event_handler/cd_handler.go, pkg/event_handler/configure_monitoring.go, pkg/event_handler/create_project.go, pkg/event_handler/handler.go, pkg/event_handler/helper.go, pkg/event_handler/problem_handler.go, pkg/lib/auto_tags.go, pkg/lib/dashboard.go, pkg/lib/dynatrace.go, pkg/lib/dynatrace_events.go, pkg/lib/dynatrace_test.go, pkg/lib/management_zones.go, pkg/lib/metric_events.go, pkg/lib/problem_comment.go, pkg/lib/problem_notifications.go, pkg/lib/service_sync.go, pkg/lib/service_sync_test.go
This PR
- Switches logging to the logrus (https://github.com/sirupsen/logrus) library
- Uses a global logger rather than passing loggers around
- Introduces structured log entries
It does not intend to change what is logged
=> Use logrus as global logger

pkg/lib/configuration.go, pkg/lib/service_sync.go
`lib.synchronizeServices()` was partially ignoring parsing errors from the `SYNCHRONIZE_DYNATRACE_SERVICES_INTERVAL_SECONDS` environment variable. This PR addresses that and moves the associated code from `pkg/lib/service_sync.go` to `pkg/lib/configuration.go` where the rest of the code accessing environment variables is located.
=> Fix parsing of sync interval environment variable

README.md, pkg/lib/configuration.go
This patch PR updates the default service synchronization interval to 60 seconds in the go code and service README. It is a continuation of #312 and addresses #311.
=> Update service sync interval default values to 60s in code and documentation

go.mod, pkg/event_handler/configure_monitoring.go
This PR removes the remaining references to the previously used `KeptnLogger` in the `ConfigureMonitoringHandler` to avoid nil pointer exceptions.
=> #346 removed references to KeptnLogger

chart/templates/deployment.yaml, chart/values.yaml, deploy/service-no-dt-setup.yaml, deploy/service.yaml
In Keptn 0.8.4, the distributor will be extended with the functionality of registering itself as a Keptn uniform integration at the Keptn's Uniform API.
Related Video with short Tutorial (part of community meeting on June 17th): https://youtu.be/oZlf1v5qUvc?t=436
To enable this feature, the following changes need to be made:
First, the image of the `distributor` container of the deployment needs to be set to `keptn/distributor:0.8.4`:
```
- name: distributor
image: keptn/distributor:0.8.4
```
Second, the following environment variables have to be added to the `distributor` container:
```
- name: VERSION
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: 'metadata.labels[''app.kubernetes.io/version'']'
- name: K8S_DEPLOYMENT_NAME
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: …
```
=> Updated configuration for upcoming Keptn 0.8.4 distributor

internal/event/helper.go, internal/event_handler/cd_handler.go, internal/event_handler/configure_monitoring.go, internal/event_handler/get_sli_handler.go, internal/event_handler/handler.go, internal/problem/action.go, internal/problem/problem_handler.go
This PR moves `problem.go` and `action.go` to `problem` package.
Along the way, `helper.go` had to be moved to its own package `event`, with some functions and structs being exported.
=> Create problem package

internal/event_handler/handler.go, internal/monitoring/configure_monitoring.go
=> moves configure_monitoring.go to own package 'monitoring'

cmd/main.go, internal/event_handler/cd_handler.go, internal/lib/auto_tags.go, internal/lib/dashboard.go, internal/lib/dynatrace.go, internal/lib/dynatrace_events.go, internal/lib/management_zones.go, internal/lib/metric_events.go, internal/lib/problem_comment.go, internal/lib/problem_notifications.go, internal/onboard/service_sync.go, internal/onboard/service_sync_test.go
This PR moves `service_sync.go` and `service_sync_test.go` to the `onboard` package. References to `DTHelper` had to be updated, which had to have `SendDynatraceAPIRequest` exported.
=> Create onboard package

internal/dynatrace/entities_client.go
This PR adds a missing `?` to the `apiPath` used in `GetKeptnManagedServices()`.
=> Fix typo in apiPath in EntitiesClient

cmd/main.go, internal/event_handler/handler.go
This PR ensures errors are logged in gotEvent() and that the event switch matches on the correct pointer types
=> Additional refactoring

internal/event_handler/handler.go
This PR prevents crashes resulting from `keptnEvent` being `nil` by returning early.
=> Handle nil keptnEvent early explicitly

internal/monitoring/configure_monitoring_event_handler.go, internal/monitoring/configure_monitoring_finished_factory.go
Looking at:
https://github.com/keptn-contrib/dynatrace-service/blob/30f9fd982bdcc2bf77bc53c114f9d8aacb4a291b/internal/monitoring/configure_monitoring_finished_factory.go#L20-L34
These methods currently don't set `eventData` of the `ConfigureMonitoringFinishedEventFactory` structs, but this is used in `getEventFactory`. This PR would rectify this.
=> Pass missing eventData to ConfigureMonitoringFinishedEventFactory

README.md, documentation/configuration.md, documentation/sli-configuration.md
This PR updates merge transformations in the documentation to use dimension keys.
Also it removes the outdated "merge in progress" message that references dynatrace-service 0.15.1 and dynatrace-sli-service 0.12.1.
=> Update documentation: Update merge transformations to use dimension keys

internal/dynatrace/dashboard.go, internal/dynatrace/dynatrace_client.go, internal/monitoring/dashboard_creation.go, internal/sli/dashboard/testdata/test_query_dynatrace_dashboard_dashboard_kqg.json
This PR fixes an issue when creating a Dynatrace dashboard while configure monitoring resp. while a new project in Keptn would be set up.
Dynatrace dashboards API would return 400 in this case.
The bug had been introduced while merging the DTOs for dashboards of **dynatrace-service** and **dynatrace-sli-service** recently.
=> fixes issues while creating a dashboard

internal/common/common.go, internal/event_handler/handler.go, internal/keptn/keptn_client.go
Introduces `keptn.NewDefaultClient()` that creates a Keptn client that uses the same service URLs used other places in the code.
=> Harmonize keptn client creation

internal/credentials/credentials_manager.go, internal/dynatrace/dynatrace_client.go, internal/monitoring/dashboard_creation.go, internal/monitoring/metric_events_creation.go
Closes #504 
This PR:
- Removes extra `https://` prefix in messages and logs
- Removes a redundant check for prefix in `dynatrace.Client`
- Documents that the `Tenant` field of `DTCredentials` should always be prefixed correctly
=> Remove extra https prefix in link in dashboard creation message

internal/dynatrace/metrics_client.go, internal/dynatrace/problems_v2_client_test.go, internal/dynatrace/security_problems_client_test.go, internal/dynatrace/slo_client_test.go, internal/dynatrace/usql_client.go, internal/keptn/keptn_client.go, internal/sli/dashboard/dashboard_querying_test.go, internal/sli/dashboard/dashboard_retrieval_test.go, internal/sli/get_sli_triggered_event_handler.go, internal/sli/get_sli_triggered_event_handler_test.go, internal/sli/query/query_processing.go, internal/sli/query/query_processing_test.go, internal/sli/test_helper_test.go, internal/sli/testdata/response_time_p95_200_0_result_warning_entity-selector.json, internal/sli/testdata/response_time_p95_200_0_result_wrong-tag.json, internal/sli/testdata/response_time_p95_200_1_result.json, internal/sli/testdata/response_time_p95_200_1_result_defaults.json, internal/sli/testdata/response_time_p95_400_constraints-violated.json, internal/test/file_based_url_handler.go, internal/test/payload_based_url_handler.go
this addresses #413
removes default fallback behaviors 
* if custom SLI definitions (in sli.yaml) could not be retrieved - will return an error now
* if custom SLI definitions (in sli.yaml) could not be parsed correctly due to invalid YAML - will return an error now
* if desired indicator could not be found in custom SLI definitions (in sli.yaml) e.g. due to a misspelled indicator - will return an error now
we still fallback to default SLI definitions in two cases:
* there is no `dynatrace/sli.yaml` file
* there is a `dynatrace/sli.yaml` file, but it has no `indicators` defined
adds more details to error messages:
* if no results could be retrieved by this query, then sometimes there is a `warning` returned by the Dynatrace API. This is now included in the `message`  of the `SLIResult`
=> No fallback to default SLIs when custom SLIs are defined (in sli.yaml) 

internal/sli/get_sli_events_factory.go, internal/sli/get_sli_triggered_event_handler.go, internal/sli/get_sli_triggered_event_handler_test.go
also the error message is added to `GetSLIFinishedEventData.message`
this closes #507
=> `GetSLIFinishedEventData.result` is now set to `fail` in case of error

internal/common/common.go, internal/problem/problem_events_factory.go, internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_sli_files_test.go, internal/sli/metrics/legacy_query_transformation.go, internal/sli/metrics/legacy_query_transformation_test.go, internal/sli/metrics/metrics_query_builder.go, internal/sli/metrics/metrics_query_builder_test.go, internal/sli/metrics/query_parsing.go, internal/sli/metrics/query_parsing_test.go
this closes #571
metric queries are now parsed differently and in case we cannot do so correctly (see example below) we will return an error accordingly.
We will handle all URI reserved characters appropriately with the exception of `?` and `&` as those are necessary for the parsing logic. So any metric query that would include these two characters in e.g. *tags* or *filters* will fail.
**See two possible options for failing metric queries:**
```{yaml}
---
spec_version: '1.0'
indicators:
error_rate: "metricSelector=builtin:service.errors.total.rate:merge(\"dt.entity.service\"):avg&entitySelector=type(SERVICE),tag(keptn_managed),tag(keptn_service:my-service),tag(my-tag:why?)"
response_time_p95: "metricSelector=builtin:service.response.time:merge(\"dt.entity.service\"):percentile(95)&entityS …
```
=> Improve parsing and validation of sli def

chart/README.md, chart/templates/_helpers.tpl, chart/templates/deployment.yaml, chart/templates/serviceaccount.yaml, chart/values.yaml
Fixes #587 
Fixing the service account name to ```dynatrace-service```, which is used by Keptn secret service
=> Fix service account name to dynatrace service

internal/sli/dashboard/metrics_query_processing.go, internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_slo_generation_test.go, internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_test.go, internal/sli/testdata/dashboards/slo_generation/data_explorer_tile_no_data/dashboard.json, internal/sli/testdata/dashboards/slo_generation/data_explorer_tile_no_data/metrics_builtin_service_response_time.json, internal/sli/testdata/dashboards/slo_generation/data_explorer_tile_no_data/metrics_query_builtin_service_response_time.json
=> fix: Custom Charting and Data Explorer dashboard tiles that return no data should produce a failed indicator value and be included in SLO objectives

documentation/slis-via-files.md
This PR corrects a small error in the PV2 documentation: management zones in entity selectors should be specified using the `mzId(...)` criterion
=> docs: Fix management zone criterion in PV2 entity selector

documentation/problem-forwarding-to-keptn.md, internal/problem/problem_event_handler.go, internal/problem/problem_event_handler_test.go, internal/problem/testdata/open_problem_no_stage/received_ce.json
=> fix: `ProblemEventHandler` sends `sh.keptn.event.[STAGE].remediation.triggered` event even if stage is not set 

internal/onboard/service_sync.go, internal/onboard/service_sync_test.go
=> fix: Service entities tagged with multiple `keptn_service` tags should produce an error

.github/workflows/validate-semantic-prs.yml
- re-uses the validate semantic PR workflow from keptn/gh-automation
Part of #655
=> build: re-use validate semantic PR workflow from keptn/gh-automation

.github/workflows/CI.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml
- re-uses the docker build action from keptn/gh-automation
**Note**: I have left out the part where we push images to ghcr.io, but I can easily add it if you want.
Part of #655
=> chore: Re-use docker-build action from keptn/gh-automation

internal/sli/dashboard/dashboard_error.go, internal/sli/get_sli_triggered_event_handler.go, internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_fails_test.go, internal/sli/testdata/sli_via_dashboard_test/dashboard_id_not_found_404.json, internal/sli/testdata/sli_via_dashboard_test/dashboard_invalid_uuid_400.json
=> fix: error messages are no longer attached to indicator from event if dashboard processing fails

README.md, documentation/dynatrace-api-token-scopes.md
Adds `dynatrace-api-token-scopes.md` to the table of contents and fixes some broken links.
=> docs: Update documentation links

chart/templates/deployment.yaml, chart/values.schema.json
This removes the option for omitting the dynatrace-service container when deploying via Helm, introduced in #513, as this is now obsolete.
=> fix: Remove helm chart option for optional dynatrace-service container deployment

documentation/troubleshooting.md
This PR improves the usability of the troubleshooting documentation by adding several cross-links
=> docs: Add cross-links to `dashboard` entry in `dynatrace/dynatrace.conf.yaml`

documentation/slis-via-dashboard.md, internal/sli/dashboard/dashboard_processing.go, internal/sli/dashboard/dashboard_querying.go, internal/sli/dashboard/markdown_tile_processing.go, internal/sli/dashboard/markdown_tile_processing_test.go, internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_markdown_test.go, internal/sli/testdata/dashboards/markdown/markdown-tile-parsing-errors-multiple-tiles-template.json, internal/sli/testdata/dashboards/markdown/markdown-tile-parsing-errors-template.json, internal/sli/testdata/dashboards/markdown/markdown-tile-parsing-single-sli-template.json, internal/test/combined_url_handler.go
closes #629 
in case an error occurs while parsing the configuration contained in a **markdown** tile and error will be returned and no evaluation of SLIs will be done.
* duplicate entries for any of the *keys*: `KQG.Total.Pass`, `KQG.Total.Warning`, `KQG.Compare.WithScore`, `KQG.Compare.Results` and `KQG.Compare.Function`
* `KQG.Total.Pass`, `KQG.Total.Warning`: any value that is not a non-negative decimal including an optional `%`. So basically anything that does not match: `^(\d+|\d+\.\d+)([%]?)$`
* `KQG.Compare.WithScore`: any value other than `pass`, `all`, `pass_or_warn`
* `KQG.Compare.Results`: any not integral value as well as integers that are less than `1`
* `KQG.Compare.Function`: any value other than `avg`, `p50`, `p90`, `p95`
=> fix!: markdown processing returns errors

internal/sli/dashboard/data_explorer_tile_processing.go, internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_data_explorer_test.go, internal/sli/testdata/dashboards/data_explorer/no_entity_type/dashboard.json, internal/sli/testdata/dashboards/data_explorer/no_entity_type/metrics_builtin_security_securityProblem_open_managementZone.json
=> fix: Data Explorer tiles using a management zone should produce an error if no entity type can be determined

go.mod, go.sum
=> chore: Update to `keptn/go-utils v0.16.1-0.20220628141633-eb5fb9ba43e0`

internal/action/action_finished_event_handler.go, internal/action/action_triggered_event_handler.go, internal/action/common.go, internal/action/common_test.go, internal/action/deployment_finished_event_handler.go, internal/action/evaluation_finished_event_handler.go, internal/action/release_triggered_event_handler.go, internal/action/test_finished_event_handler.go, internal/action/test_triggered_event_handler.go, internal/keptn/common.go
This PR will add a new custom property `evaluationHeatmapURL` with the direct back link to the evaluation page in Keptn Bridge
relates to #240
=> feat: add new custom property `evaluationHeatmapURL` to evaluation finished events

.github/workflows/build-helm-chart.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml, gh-actions-scripts/build_helm_chart.sh
we do no longer need the distributor version in `values.yaml` so this has been removed
=> ci: remove distributor version from in release actions

documentation/event-forwarding-to-dynatrace-to-specific-entities.md
=> docs: removes duplicate sections

documentation/sli-provider.md, internal/sli/dashboard/custom_charting_tile_processing.go, internal/sli/dashboard/data_explorer_tile_processing.go, internal/sli/dashboard/metric_query_components.go, internal/sli/dashboard/metrics_query_processing.go, internal/sli/dashboard/metrics_query_processing_test.go, internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_custom_charting_test.go, internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_data_explorer_test.go, internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_slo_generation_test.go, internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_test.go, internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_sli_files_metrics_query_test.go, internal/sli/query/query_processing.go, internal/sli/query/query_processing_test.go, internal/sli/unit/units.go, internal/sli/unit/units_test.go
This PR:
- removes automatic conversion of microseconds to milliseconds for `builtin:service.response.time` metric
- removes automatic conversion of microseconds to milliseconds or bytes to kilobytes for dashboard-based Metrics-V2-based  SLIs
- provides examples of how to achieve the same functionality using `:toUnit(...)` transformation or `MV2;` prefix
=> feat!: Remove automatic conversion of `builtin:service.response.time` as well as microsecond and byte units

internal/sli/dashboard/markdown_tile_processing.go, internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_markdown_test.go
This PR:
- trims whitespace from key-value pairs from markdown tiles
This prevents also issues with additional whitespace at the end of markdown tiles.
=> fix: Trim whitespace from key-value pairs in markdown tiles

internal/sli/dashboard/data_explorer_tile_processing.go, internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_data_explorer_test.go, internal/sli/testdata/dashboards/data_explorer/no_spaceag_no_filterby/dashboard_no_spaceag_no_filterby.json, internal/sli/testdata/dashboards/data_explorer/no_spaceag_no_filterby/metrics_query_builtin_service_response_time_auto.json
This PR adds support to branch 0.23.x for auto space aggregation in Data Explorer tiles by making auto the default when no space aggregation is specified.
=> fix: Support auto space aggregation

.github/workflows/CI.yml
Signed-off-by: Dietmar Schnitzer <103405584+dietmar-91@users.noreply.github.com>
=> ci: remove token from checkout action in verify-next-version job

internal/sli/get_sli_triggered_event_handler.go, internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_sli_files_test.go, internal/sli/test_helper_test.go
=> fix: Generate specific error message if no SLIs are requested when using file-based SLIs

chart/templates/deployment.yaml, documentation/additional-installation-options.md, go.mod, go.sum, internal/env/configuration.go, internal/keptn/common.go
this will include go-utils `0.19.0` in order to achieve compatibility for Keptn `0.19.0` release
=> feat!: add support for keptn 0.19

.github/workflows/CI.yml, .github/workflows/create-release-pr.yml, .github/workflows/create-release.yml
- update deprecated set-output workflow command in release-please workflows (https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
- change pr-title-pattern of release-please
- remove release branches from on_pull_request event in ci workflow because through the branch protection rule the ci pipeline (ci_prepare_run, docker_build, unit_test) gets also triggered
=> ci: update release-please workflow

renovate.json
Disable `gomodMassage` option to see whether we can get rid of the artifacts from this renovate PR #1009 
We do not have any `replace` statements anyway, [but `keptn/go-utils` does](https://github.com/keptn/go-utils/blob/master/go.mod#L89-L96)
See [this explanation from renovate](https://github.com/keptn-contrib/dynatrace-service/pull/1010)
> Renovate can massage `replace` statements it finds prior to running `go` commands, and then massage them back afterwards. This capability was added - and originally default behavior - because relative `replace` statements outside of the current repo will not work when Renovate clones the repo locally. 
>
> On the other hand, this massaging of `replace` statements may lead to unexpected results, especially because `go mod tidy` may not fully tidy the …
=> build: disable gomodMassage in renovate bot
