keptn-contrib/dynatrace-service

- releasenotes/releasenotes_V0.1.0.md
- releasenotes/releasenotes_V0.1.1.md
- releasenotes/releasenotes_develop.md
Added missing release notes files.
> Updated release notes

- .gitignore
- Dockerfile
- deploy/scripts/applyAutoTaggingRules.sh
- deploy/scripts/setupProblemNotification.sh
- main.go
- releasenotes/releasenotes_develop.md
- skaffold.yaml
- Use CUSTOM_PROP for auto-tagging rules
> #1110 Change auto tagging rules to use custom prop

- deploy/service.yaml
- pkg/lib/dynatrace.go
- Reading Keptn namespace from environment variable to allow adding the Dynatrace service to Keptn installations in cutom namespaces.
> Dynamic keptn namespace

- .github/workflows/reviewdog.yml
- .reviewdog.yml
This PR updates our reviewdog configuration and fixes some issues with golint
> Fixing reviewdog issues

- deploy/service-no-dt-setup.yaml
- deploy/service.yaml
- go.mod
- go.sum
- pkg/adapter/deploymentfinished_adapter.go
- pkg/adapter/evaluationdone_adapter.go
- pkg/adapter/evaluationfinished_adapter.go
- pkg/adapter/releasetriggered_adapter.go
- pkg/common/common.go
- pkg/event_handler/cd_handler.go
> #203 Adapt to next-gen events

- .github/workflows/reviewdog.yml
- go.mod
- go.sum
- pkg/event_handler/configure_monitoring.go
- pkg/event_handler/create_project.go
- pkg/lib/auto_tags.go
- pkg/lib/dashboard.go
- pkg/lib/dynatrace.go
- pkg/lib/management_zones.go
- pkg/lib/metric_events.go
- pkg/lib/problem_notifications.go
> #211 send configure-monitoring.finished events instead of websocket logging

- pkg/event_handler/problem_handler.go
- pkg/lib/dynatrace_api_models.go
> #213 add shkeptncontext and use CE 1.0 for Problem notifications

- README.md
- deploy/service.yaml
- pkg/event_handler/problem_handler.go
- pkg/lib/metric_events.go
- pkg/lib/service_sync.go
- releasenotes/releasenotes_V0.10.1.md
- releasenotes/releasenotes_V0.10.2.md
Signed-off-by: Andreas Grabner <grabnerandi@gmx.at>
> implementing fixes

- .github/workflows/CI.yml
Signed-off-by: Christian Kreuzberger <christian.kreuzberger@dynatrace.com>
This PR fixes GH workflow CI.yml for external contributors
> Fix gh workflow CI.yaml for external contributor

- README.md
- deploy/service.yaml
- pkg/lib/configuration.go
- pkg/lib/dynatrace_api_models.go
- releasenotes/releasenotes_V0.10.3.md
Signed-off-by: jetzlstorfer <juergen.etzlstorfer@dynatrace.com>
> introduce flag to make dashboard env-wide public

- .github/dependabot.yml
- .github/workflows/CI.yml
Signed-off-by: Christian Kreuzberger <christian.kreuzberger@dynatrace.com>
* Added dependabot config for automated dependency updates
* Updated CI workflow to use docker login action
> Added dependabot, use docker login action

- go.mod
- go.sum
- pkg/adapter/deploymentfinished_adapter.go
- pkg/common/common.go
> #219 Fixed CloudEvent decoding

- pkg/common/common.go
- pkg/lib/service_sync.go
> #252 adapt endpoints for project/service retrieval

- deploy/service-no-dt-setup.yaml
- deploy/service.yaml
Signed-off-by: Christian Kreuzberger <christian.kreuzberger@dynatrace.com>
> Update distributor to 0.8.0

- README.md
- deploy/service-no-dt-setup.yaml
- deploy/service.yaml
Signed-off-by: warber <bernd.warmuth@dynatrace.com>
> prepare release 0.11.0

- README.md
- go.mod
- go.sum
- releasenotes/releasenotes_V0.12.0.md
> Prepare release 0.12.0

- .github/workflows/CI.yml
- .github/workflows/create_release_draft.yml
- README.md
- chart/.helmignore
- chart/Chart.yaml
- chart/README.md
- chart/templates/_helpers.tpl
- chart/templates/deployment.yaml
- chart/templates/service.yaml
- chart/templates/serviceaccount.yaml
- chart/templates/tests/test-api-connection.yaml
- chart/values.schema.json
- chart/values.yaml
- deploy/service-no-dt-setup.yaml
- deploy/service.yaml
- gh-actions-scripts/build_helm_chart.sh
- skaffold.yaml
> #261 helm chart for dynatrace-service

- deploy/service-no-dt-setup.yaml
- deploy/service.yaml
> updated image tags

- Dockerfile
- chart/templates/deployment.yaml
- chart/values.yaml
- deploy/service-no-dt-setup.yaml
- deploy/service.yaml
Closes #292
Signed-off-by: Andreas Grimmer <andreas.grimmer@dynatrace.com>
> Run container as non-root, set securityContext

- go.mod
- go.sum
> Update go-utils to v0.8.3

- chart/Chart.yaml
- chart/values.yaml
- deploy/service-no-dt-setup.yaml
- deploy/service.yaml
- releasenotes/releasenotes_V0.12.0.md
- releasenotes/releasenotes_V0.13.0.md
- releasenotes/releasenotes_develop.md
> Prepare release 0.13

- chart/Chart.yaml
- chart/values.yaml
- deploy/service-no-dt-setup.yaml
- deploy/service.yaml
- releasenotes/releasenotes_V0.12.0.md
- releasenotes/releasenotes_V0.13.0.md
- releasenotes/releasenotes_develop.md
> Release 0.13.0

- chart/values.schema.json
Signed-off-by: Andreas Grimmer <andreas.grimmer@dynatrace.com>
> Allow repos starting with numbers

- CODEOWNERS
- chart/values.yaml
- deploy/service-no-dt-setup.yaml
- deploy/service.yaml
Closes #311
Signed-off-by: Andreas Grimmer <andreas.grimmer@dynatrace.com>
> Decrease sync interval to 60 sec

- README.md
- chart/README.md
- chart/templates/deployment.yaml
- chart/values.schema.json
- chart/values.yaml
- pkg/lib/dynatrace.go
- pkg/lib/dynatrace_test.go
> add https_proxy/http_proxy env var support

- chart/templates/deployment.yaml
> #180 Patched helm deployment

- README.md
Not sure why the last line is being highlighted as part of the change. I'm doing all in GitHub's web browser UI.
> Use --dry-run=client

- README.md
- pkg/lib/service_sync.go
- pkg/lib/service_sync_test.go
> Removed entity ID fallback for service names

- pkg/lib/service_sync.go
> Dynatrace Service Synchronization must also work with Environment Tags

- releasenotes/releasenotes_V0.14.0.md
> Added release notes v0.14.0

- pkg/lib/dynatrace.go
fixes #323 
Signed-off-by: warber <bernd.warmuth@dynatrace.com>
> Fixed base url used for creating the service handler

- README.md
- releasenotes/releasenotes_V0.15.0.md
This PR:
- Adds the release notes for v0.15.0
- Updates the compatibility matrix
- Includes a rewritten installation section in `README.md`
- Fixes a few small issues in `README.md`
> Add release notes and update README.md for v0.15.0 

- sonar-project.properties
This PR adds the properties file to enable Sonar Cloud for the repository.
> Enable Sonar Cloud

- .github/workflows/sonarcloud.yml
- sonar-project.properties
This PR adds a SonarCloud workflow
> Add SonarCloud workflow 

- chart/templates/deployment.yaml
- chart/values.yaml
Implementing issue https://github.com/keptn/keptn/issues/4590 in the dynatrace-service
> Allow to set the metadata for the node and namespace

- README.md
> Fix links to documentation in README.md

- README.md
> Add notice informing users about status of merge

- README.md
- releasenotes/releasenotes_V0.16.0.md
The PR contains release notes for 0.16.0 and updated the README.md
> Release 0.16.0

- .github/workflows/create_release_draft.yml
Fixes #421 by manually setting the RUN_ID to env variables
> Manual extraction of RUN_ID for workflow

- pkg/event_handler/get_sli_handler.go
- pkg/lib/dynatrace/dashboard_query.go
- pkg/lib/dynatrace/dynatrace.go
- pkg/lib/dynatrace/dynatrace_test.go
breaks down the SLO/SLI retrieval from different dashboard tile types to separate methods
this again addresses #412
> refactor logic of dashboard processing

- skaffold.yaml
> Remove reuse-values option from skaffold.yaml

- internal/dynatrace/auto_tags_client.go
- internal/dynatrace/dynatrace.go
- internal/dynatrace/dynatrace_api_models.go
- internal/dynatrace/dynatrace_api_models_test.go
- internal/dynatrace/dynatrace_events.go
- internal/dynatrace/dynatrace_test.go
- internal/dynatrace/problem_comment.go
- internal/event_handler/cd_handler.go
- internal/event_handler/create_project.go
- internal/monitoring/auto_tags.go
- internal/monitoring/configuration.go
- internal/monitoring/configure_monitoring.go
- internal/monitoring/dashboard.go
- internal/monitoring/management_zones.go
- internal/monitoring/metric_events.go
- internal/monitoring/problem_notifications.go
- internal/onboard/service_sync.go
- internal/onboard/service_sync_test.go
- internal/problem/action.go
creates client that hides the complexity of REST requests on Dynatrace auto-tags resource
addresses #426
> refactors auto-tags creation

- internal/dynatrace/alerting_profiles_client.go
- internal/dynatrace/auto_tags_client.go
- internal/dynatrace/dashboards_client.go
- internal/dynatrace/dynatrace.go
- internal/dynatrace/dynatrace_api_models.go
- internal/dynatrace/helper.go
- internal/dynatrace/management_zones_client.go
- internal/dynatrace/notifications_client.go
- internal/monitoring/auto_tags.go
- internal/monitoring/dashboard.go
- internal/monitoring/management_zones.go
- internal/monitoring/metric_events.go
- internal/monitoring/problem_notifications.go
several pieces have been touched
- auto tags creation
- dashboard creation
- management zone creation
- problem notification creation
addresses #426
> refactor configure monitoring clients

- internal/adapter/cloud_event_adapter.go
- internal/event_handler/handler.go
- internal/event_handler/no_op_handler.go
- internal/monitoring/configure_monitoring_event_handler.go
- internal/monitoring/configuremonitoring_adapter.go
- internal/monitoring/create_project_event_handler.go
- internal/problem/action_finished_event_handler.go
- internal/problem/action_started_event_handler.go
- internal/sli/get_sli_handler.go
- internal/sli/get_sli_triggered_adapter.go
removes all external dependencies on cloud events on event handler level
there are still some internal dependencies when cloud events are created
addresses #426
> reduce dependencies on cloud events in event handlers

- .github/workflows/CI.yml
This PR enables workflow dispatch of CI Action. Once enabled, it should be possible to test changes to CI on a branch.
> Enable workflow dispatch

- documentation/configuration.md
This PR updates the shipyard presented in the documentation to a full file rather than a snippet
> Documentation: Update basic shipyard.yaml

- README.md
- releasenotes/releasenotes_V0.17.0.md
> adds new release notes for upcoming release 0.17.0

- internal/sli/get_sli_triggered_event_handler_test.go
- internal/sli/testdata/response_time_p95_200_3_results.json
> adds missing test for multiple return values by metric query

- chart/values.yaml
This PR will add default resource limits and requests to the dynatrace-service container and adding a default seccompProfile to it.
> add securityContext, resource limits and requests

- README.md
- chart/values.yaml
- releasenotes/releasenotes_V0.18.0.md
Preparation for release of 0.18.0
> Prepare for release 0.18.0

- internal/sli/dashboard/custom_charting_tile_processing.go
- internal/sli/dashboard/dashboard_query.go
- internal/sli/dashboard/data_explorer_tile_processing.go
- internal/sli/dashboard/metrics_query_processing.go
- internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_custom_charting_test.go
- internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_slo_generation_test.go
- internal/sli/testdata/dashboards/slo_generation/supported_data_explorer_tile/dashboard.json
- internal/sli/testdata/dashboards/slo_generation/supported_data_explorer_tile/metrics_builtin_service_response_time.json
- internal/sli/testdata/dashboards/slo_generation/supported_data_explorer_tile/metrics_query_builtin_service_response_time.json
- internal/sli/testdata/dashboards/slo_generation/unsupported_data_explorer_tile/dashboard.json
- internal/sli/testdata/dashboards/slo_generation/unsupported_data_explorer_tile/metrics_builtin_service_response_time.json
> fix: Ensure unsupported dashboard tiles add objectives to SLO files

- internal/event_handler/error_handler.go
- internal/event_handler/handler.go
- internal/monitoring/configure_monitoring_event_handler.go
- internal/monitoring/configure_monitoring_finished_factory.go
- internal/sli/get_sli_events_factory.go
- internal/sli/get_sli_triggered_event_handler.go
> fix: No get-sli.finished event is sent if Dynatrace credentials cannot be found

- .github/dependabot.yml
- .github/workflows/validate-semantic-prs.yml
- .versionrc.json
- Adds the semantic PR check
- Adds a .versionrc.json file that maps the semantic PR titles to certain headlines (used for release note generation later)
- Adapt dependabot config to create PRs with semantic PR titles
> chore: Added semantic PR checks

- internal/common/common.go
- internal/config/dynatrace_config_getter.go
- internal/config/dynatrace_config_getter_test.go
> fix:  Only support Keptn placeholders in values in dynatrace/dynatrace.conf.yaml where it makes sense

- internal/event_handler/error_event_factory.go
> fix: Use event type as task for non-task events

- documentation/auto-tenant-configuration.md
- documentation/problem-forwarding-to-keptn.md
- internal/dynatrace/notifications_client.go
- internal/keptn/keptn_config_resource_client.go
- internal/monitoring/auto_tags_creation.go
- internal/monitoring/configuration.go
- internal/monitoring/configure_monitoring_event_handler.go
- internal/monitoring/dashboard_creation.go
- internal/monitoring/management_zones_creation.go
- internal/monitoring/metric_events_creation.go
- internal/monitoring/problem_notification_creation.go
> fix:  Ensure problem notifications created using `keptn configure monitoring` refer to a valid project

- internal/event_handler/handler.go
> fix: Improve errors when unable to process events

- .github/actions/unit-tests/action.yml
- .github/workflows/CI.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- introduces a re-usable unit test action within this repo
- adds this unit test action to CI, pre-release and release workflow
- re-uses the prepare-ci workflow from [keptn/gh-automation](https://github.com/keptn/gh-automation/#workflows)
Part of #655
> chore: Improve CI pipeline and make unit tests reusable

- internal/sli/dashboard/slo_tile_processing.go
- internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_slo_tile_test.go
- internal/sli/testdata/dashboards/slo_tiles/tile_empty_slo_id/dashboard.json
- internal/sli/testdata/dashboards/slo_tiles/tile_no_slo_ids/dashboard.json
- internal/sli/testdata/dashboards/slo_tiles/unknown_slo_id/dashboard.json
- internal/sli/testdata/dashboards/slo_tiles/unknown_slo_id/slo_7d07efde-b714-3e6e-ad95-08490e2540c5.json
> fix: Ensure SLO tile processing always produces an indicator

- internal/dynatrace/problems_v2_client.go
- internal/dynatrace/problems_v2_client_test.go
- internal/dynatrace/security_problems_client.go
- internal/sli/dashboard/problem_tile_processing.go
- internal/sli/dashboard/security_problem_tile_processing.go
- internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_problem_tile_test.go
- internal/sli/test_helper_test.go
- internal/sli/testdata/dashboards/problem_tile/custom_management_zone/dashboard.json
- internal/sli/testdata/dashboards/problem_tile/custom_management_zone/problems_status_open.json
- internal/sli/testdata/dashboards/problem_tile/custom_management_zone/security_problems_status_open.json
- internal/sli/testdata/dashboards/problem_tile/missing_scopes/dashboard.json
- internal/sli/testdata/dashboards/problem_tile/missing_scopes/problems_missing_scope.json
- internal/sli/testdata/dashboards/problem_tile/missing_scopes/security_problems_missing_scope.json
- internal/sli/testdata/dashboards/problem_tile/problem_tile_success/dashboard.json
- internal/sli/testdata/dashboards/problem_tile/problem_tile_success/problems_status_open.json
- internal/sli/testdata/dashboards/problem_tile/problem_tile_success/security_problems_status_open.json
> fix: Ensure problem tile processing always produces indicators

- documentation/slis-via-dashboard.md
- documentation/slis-via-files.md
- internal/dynatrace/dashboard.go
- internal/sli/dashboard/usql_tile_processing.go
- internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_usql_tile_test.go
- internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_sli_files_usql_test.go
- internal/sli/query/query_processing.go
- internal/sli/testdata/usql_200_multiple_results.json
- internal/sli/v1/usql/query.go
- internal/sli/v1/usql/query_parser_test.go
> feat: Add support for the line chart visualization type in USQL queries and dashboard tiles

- .github/workflows/pre-release.yml
fixes broken pre-release workflow:
verified with https://github.com/keptn-contrib/dynatrace-service/actions/runs/2026992626
> ci: fix pre release workflow

- documentation/dynatrace-conf-yaml-file.md
> docs: Use `spec_version`

- README.md
Signed-off-by: Andreas Grimmer <andreas.grimmer@dynatrace.com>
> docs: Fix compatibility

- CHANGELOG.md
- README.md
- documentation/installation.md
This PR updates documentation with hints for installing with Keptn 0.14.1
> docs: Provide a workaround for Keptn 0.14.1 installation

- documentation/project-setup.md
> docs: Update doc to be aligned with official Dynatrace documentation

- documentation/project-setup.md
> docs: Added a note to not exclude http usage

- cmd/main.go
- internal/common/common.go
- internal/event_handler/handler.go
- internal/keptn/client_factory.go
- internal/keptn/common.go
- internal/keptn/keptn_api_client.go
- internal/keptn/keptn_client.go
- internal/keptn/service_client.go
- internal/onboard/service_sync.go
This PR is a follow up to #767 fixing it to use correct URLs in Keptn API clients.
> fix: Use correct URLs in Keptn API clients

- internal/action/release_triggered_event_handler.go
> fix: description cannot be empty for event in release triggered handler

- README.md
- documentation/event-forwarding-to-dynatrace-to-specific-entities.md
- documentation/event-forwarding-to-dynatrace.md
> docs: adding documentation for events on PGI level

- cmd/main.go
> fix: Disconnect `nats.NatsConnector` on shutdown

- README.md
> chore: remove warning for distributor from README.md

- documentation/event-forwarding-to-dynatrace-to-specific-entities.md
- documentation/installation.md
- documentation/project-setup.md
- documentation/slis-via-dashboard.md
- documentation/troubleshooting_restore-keptn-wildcard-subscriptions.md
> fix: Update links to point to Keptn 0.16.x documentation

- .github/workflows/release.yml
> ci: makes releases drafts again

- internal/event_handler/handler.go
A proposal to improve the structure of the log message
> feat: Improve structure of created event adapter log message

- internal/sli/dashboard/usql_tile_processing.go
- internal/sli/get_sli_triggered_event_handler_retrieve_metrics_from_dashboard_usql_tile_test.go
> feat: Add dimension name to display name for USQL tiles

- internal/dynatrace/dashboards_client.go
- internal/dynatrace/dynatrace_api_models.go
- internal/dynatrace/entities_client.go
- internal/dynatrace/metric_events_client.go
- internal/dynatrace/notifications_client.go
- internal/dynatrace/problems_client.go
- internal/dynatrace/problems_v2_client.go
- internal/dynatrace/slo_client.go
- internal/keptn/config_client.go
- internal/onboard/service_sync.go
- internal/onboard/service_sync_test.go
* fix: Urlencoding of entities client
Signed-off-by: Vijay Kumar Prabhu <vijay.kumar@signavio.com>
* fix: test Urlencoding of entities client
Signed-off-by: Vijay Kumar Prabhu <vijay.kumar@signavio.com>
Signed-off-by: Vijay Kumar Prabhu <vijay.kumar@signavio.com>
> fix: Correctly encode requests made by `dynatrace.EntitiesClient`

- CHANGELOG.md
- README.md
- documentation/compatibility.md
- x-release-please-version.json
* build: release  0.25.0
Signed-off-by: Keptn Contrib Bot <keptn-contrib-bot@users.noreply.github.com>
* chore: add special version bumps
Signed-off-by: Keptn Contrib Bot <keptn-contrib-bot@users.noreply.github.com>
Signed-off-by: Keptn Contrib Bot <keptn-contrib-bot@users.noreply.github.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Keptn Contrib Bot <keptn-contrib-bot@users.noreply.github.com>
> build: release  0.25.0 (#964)

- documentation/sli-provider.md
- internal/sli/get_sli_triggered_event_handler.go
> chore: Remove automatic problem remediation SLI and SLO from `get-sli.triggered` handler

- CHANGELOG.md
- README.md
- documentation/compatibility.md
- x-release-please-version.json
> docs: release 0.26.0

- CHANGELOG.md
- README.md
- documentation/compatibility.md
- x-release-please-version.json
* build: release  0.27.0
* chore: add special version bumps
---------
> build: release  0.27.0 (#999)
